version: 4.0.{build}
image: Visual Studio 2017
build_script:
- ps: >-
    dotnet build -c Release
test_script:
- ps: >-
    dotnet test src/TestRunner/Xunit/Kekiri.Examples.Xunit

    dotnet test src/TestRunner/NUnit/Kekiri.Examples.NUnit
artifacts:
- path: src\**\bin\Release\*.nupkg
skip_tags: true
