#!/bin/sh

config=Release

rm ./package/$config -rf
./build //p:Configuration=$config

packages=`ls ./package/$config/$1*.nupkg`
echo "Publishing packages: $packages"

for pkg in $packages
do
  ./.nuget/nuget.exe push $pkg
done