using System.Reflection;
using Microsoft.Testing.Platform.Builder;

namespace Behavior;

/// <summary>
/// What the entry point generated by Microsoft.Testing.Platform.MSBuild calls, registered by
/// the TestingPlatformBuilderHook item in this package's props. A test project therefore needs
/// no Program.cs; one that writes its own calls <see cref="TestApplicationBuilderExtensions.AddBehavior"/>
/// instead.
/// </summary>
public static class TestingPlatformBuilderHook
{
    public static void AddExtensions(ITestApplicationBuilder builder, string[] arguments)
    {
        builder.AddBehavior(Assembly.GetEntryAssembly());
    }
}
