<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Copyright>2012-2026</Copyright>
    <Authors>Chris Peterson</Authors>
    <Description>A .NET framework that supports writing low-ceremony BDD tests using Gherkin language.</Description>
    <TargetFramework>net8.0</TargetFramework>
    <DebugType>portable</DebugType>
    <AssemblyName>Kekiri</AssemblyName>
    <PackageId>Kekiri</PackageId>
    <PackageTags>bdd;scenario;test;gherkin;cucumber;pickles;nunit;xunit;specflow</PackageTags>
    <PackageReleaseNotes>
Changes:

- Target net8.0 (was netstandard2.0)
- Upgrade dependencies
    </PackageReleaseNotes>
    <PackageProjectUrl>https://github.com/chris-peterson/kekiri#overview</PackageProjectUrl>
    <RepositoryUrl>https://github.com/chris-peterson/kekiri</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>6.0.0</Version>
  </PropertyGroup>

</Project>
