<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Kekiri\Kekiri.csproj" />
    <ProjectReference Include="..\..\..\IoC\Kekiri.IoC.Autofac\Kekiri.IoC.Autofac.csproj" />
    <ProjectReference Include="..\Kekiri.Xunit\Kekiri.Xunit.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>
</Project>
